name       : python-rich
version    : 12.6.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/r/rich/rich-12.6.0.tar.gz : ba3a3775974105c221d31141f2c116f4fd65c5ceb0698657a11e9f295ec93fd0
homepage   : https://github.com/Textualize/rich
license    : MIT
component  : programming.python
summary    : Rich is a Python library for rich text and beautiful formatting in the terminal
description: |
    Rich is a Python library for rich text and beautiful formatting in the terminal. The Rich API makes it easy to add color and style to terminal output. Rich can also render pretty tables, progress bars, markdown, syntax highlighted source code, tracebacks, and more — out of the box.
rundeps    :
    - pygments
    - python-commonmark
build      : |
    %python3_setup
install    : |
    %python3_install
